apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-chart
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure # Specify the restart policy here
          containers:
          - name: helm-chart
            image: linuxcontainerregistry01.azurecr.io/cronjob:v56
            command:
              - python
              - /app/cron_task.py
          restartPolicy: Never
