apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-chart-helm-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-chart
  template:
    metadata:
      labels:
        app: helm-chart
    spec:
      containers:
      - name: helm-chart
        image: linuxcontainerregistry01.azurecr.io/cronjob:v60
        command: ["python", "/app/cron_task.py"]
      restartPolicy: Always
